import { describe, expect, it } from "vitest";
import { runTriage } from "../src/commands/triage.js";
import type { GhContext } from "../src/runtime/gh.js";
import type { ExecFn, ExecOutput } from "../src/runtime/exec.js";
import type { TrustPolicy } from "../src/core/trust-gate.js";

// End-to-end coverage of the trust-gated `dev triage` flow against a FAKE `gh`
// (#751 acceptance #4): trusted ⇒ auto, untrusted ⇒ no-op until summon,
// summon ⇒ triage runs. The fake routes each `gh` invocation by its argv so a
// single recorder can answer the author/labels reads AND record the writes.

interface FakeGh {
  exec: ExecFn;
  calls: { cmd: string; args: string[] }[];
  edits: { remove: string[]; add: string[] }[];
  comments: string[];
  closes: number[];
}

function fakeGh(author: string, labels: string[] = ["needs-triage"]): FakeGh {
  const calls: { cmd: string; args: string[] }[] = [];
  const edits: { remove: string[]; add: string[] }[] = [];
  const comments: string[] = [];
  const closes: number[] = [];

  const ok = (stdout = ""): ExecOutput => ({ code: 0, stdout, stderr: "" });

  const exec: ExecFn = (cmd, argv) => {
    const args = [...argv];
    calls.push({ cmd, args });
    const has = (s: string) => args.includes(s);

    if (has("view") && has("--json") && args[args.indexOf("--json") + 1] === "author") {
      return Promise.resolve(ok(JSON.stringify({ author: { login: author } })));
    }
    if (has("view") && has("--json") && args[args.indexOf("--json") + 1] === "labels") {
      return Promise.resolve(ok(JSON.stringify({ labels: labels.map((name) => ({ name })) })));
    }
    if (has("edit")) {
      const remove: string[] = [];
      const add: string[] = [];
      for (let i = 0; i < args.length; i += 1) {
        if (args[i] === "--remove-label") remove.push(args[++i]!);
        if (args[i] === "--add-label") add.push(args[++i]!);
      }
      edits.push({ remove, add });
      return Promise.resolve(ok());
    }
    if (has("comment")) {
      comments.push(args[args.indexOf("--body") + 1] ?? "");
      return Promise.resolve(ok());
    }
    if (has("close")) {
      closes.push(Number(args[args.indexOf("close") + 1]));
      return Promise.resolve(ok());
    }
    // label create (ensureLabel) and anything else: succeed quietly.
    return Promise.resolve(ok());
  };

  return { exec, calls, edits, comments, closes };
}

const strict: TrustPolicy = { enabled: true, allowlist: ["alice"] };
const permissive: TrustPolicy = { enabled: false, allowlist: [] };

function ctxFor(fake: FakeGh): GhContext {
  return { cwd: "/r", repo: "acme/widgets", exec: fake.exec };
}

describe("runTriage — trusted author auto-triages", () => {
  it("applies the decided transition with no summon", async () => {
    const fake = fakeGh("alice");
    const outcome = await runTriage(ctxFor(fake), strict, {
      issue: 42,
      decision: "ready-for-agent",
      summon: false,
    });

    expect(outcome.action).toBe("auto-triage");
    expect(outcome.applied?.decision).toBe("ready-for-agent");
    expect(fake.edits).toEqual([{ remove: ["needs-triage"], add: ["ready-for-agent"] }]);
    expect(fake.comments[0]).toContain("This was generated by AI during triage");
    expect(fake.closes).toEqual([]);
  });

  it("auto-triages everything under a permissive policy", async () => {
    const fake = fakeGh("a-total-stranger");
    const outcome = await runTriage(ctxFor(fake), permissive, {
      issue: 7,
      decision: "needs-info",
      summon: false,
    });
    expect(outcome.action).toBe("auto-triage");
    expect(fake.edits).toEqual([{ remove: ["needs-triage"], add: ["needs-info"] }]);
  });

  it("wontfix closes the issue after the transition", async () => {
    const fake = fakeGh("alice");
    await runTriage(ctxFor(fake), strict, { issue: 9, decision: "wontfix", summon: false });
    expect(fake.edits).toEqual([{ remove: ["needs-triage"], add: ["wontfix"] }]);
    expect(fake.closes).toEqual([9]);
  });
});

describe("runTriage — untrusted author is a NO-OP until summon", () => {
  it("does not edit labels, comment, or close when untrusted and unsummoned", async () => {
    const fake = fakeGh("stranger");
    const outcome = await runTriage(ctxFor(fake), strict, {
      issue: 99,
      decision: "ready-for-agent",
      summon: false,
    });

    expect(outcome.action).toBe("hold-for-summon");
    expect(outcome.reason).toContain("untrusted author 'stranger'");
    expect(fake.edits).toEqual([]);
    expect(fake.comments).toEqual([]);
    expect(fake.closes).toEqual([]);
  });

  it("an unknown author (gh read failed) is also held", async () => {
    const fake = fakeGh("");
    // Force the author read to fail entirely.
    const failing: GhContext = {
      cwd: "/r",
      repo: "acme/widgets",
      exec: (cmd, argv) => {
        const args = [...argv];
        if (args.includes("--json") && args[args.indexOf("--json") + 1] === "author") {
          return Promise.resolve({ code: 1, stdout: "", stderr: "not found" });
        }
        return fake.exec(cmd, argv, { cwd: "/r" });
      },
    };
    const outcome = await runTriage(failing, strict, {
      issue: 5,
      decision: "ready-for-agent",
      summon: false,
    });
    expect(outcome.action).toBe("hold-for-summon");
    expect(fake.edits).toEqual([]);
  });
});

describe("runTriage — maintainer summon releases an untrusted author's issue", () => {
  it("the --summon flag releases the issue and applies the transition", async () => {
    const fake = fakeGh("stranger");
    const outcome = await runTriage(ctxFor(fake), strict, {
      issue: 99,
      decision: "ready-for-agent",
      summon: true,
    });

    expect(outcome.action).toBe("auto-triage");
    expect(fake.edits).toEqual([{ remove: ["needs-triage"], add: ["ready-for-agent"] }]);
    expect(fake.comments[0]).toContain("released by maintainer summon");
  });

  it("the triage:summon label is also a summon channel and is shed on apply", async () => {
    const fake = fakeGh("stranger", ["needs-triage", "triage:summon"]);
    const outcome = await runTriage(ctxFor(fake), strict, {
      issue: 100,
      decision: "ready-for-human",
      summon: false,
    });

    expect(outcome.action).toBe("auto-triage");
    expect(fake.edits).toEqual([
      { remove: ["needs-triage", "triage:summon"], add: ["ready-for-human"] },
    ]);
  });
});
