// `dev triage` — apply a `/triage` decision outcome to an issue, GATED by the
// trust-aware auto-triage router (#751, parent PRD #745).
//
// The maintainer/agent supplies the DECISION (`--decision <state>`) that `/triage`
// reached; this command applies the canonical label transition, but only when the
// issue is eligible to auto-triage:
//
//   - TRUSTED author (or a permissive repo)  → applies the transition.
//   - UNTRUSTED public author, no summon      → NO-OP; the issue waits for a
//     maintainer to summon triage.
//   - Maintainer SUMMON (`--summon` flag, or the `triage:summon` label present)
//     → releases an untrusted author's issue and applies the transition.
//
// The pure router + transition planner live in core/auto-triage.ts; this module
// is the gh-backed orchestrator. `runTriage` takes an injectable GhContext so the
// whole flow is drivable against a fake `gh` in tests.

import {
  isAuthorTrusted,
  isTriageDecision,
  planTriageTransition,
  routeNeedsTriage,
  TRIAGE_DECISIONS,
  type AutoTriageAction,
  type TriageDecision,
  type TriageTransition,
} from "../core/auto-triage.js";
import { LABEL_TRIAGE_SUMMON } from "../core/triage-labels.js";
import { parseTrustPolicy, type TrustPolicy } from "../core/trust-gate.js";
import { loadConfig } from "../core/config.js";
import {
  closeIssue,
  comment,
  editLabels,
  ensureLabel,
  issueAuthor,
  viewLabels,
  type GhContext,
} from "../runtime/gh.js";
import { resolveConfigPath } from "./route-model-tier.js";
import { resolveRepoContext } from "../runtime/wire.js";

/** The verbatim disclaimer every triage-authored comment must carry (triage SKILL). */
const TRIAGE_DISCLAIMER = "> *This was generated by AI during triage.*";

export interface TriageOptions {
  issue: number;
  /** The decided `/triage` outcome to apply (required to apply a transition). */
  decision: TriageDecision;
  /** Explicit maintainer summon — releases an untrusted author's issue. */
  summon: boolean;
}

export interface TriageOutcome {
  issue: number;
  action: AutoTriageAction;
  author?: string;
  /** Set only when the transition was applied. */
  applied?: { decision: TriageDecision; transition: TriageTransition };
  /** Human-readable reason, set when HELD. */
  reason?: string;
}

/**
 * Resolve trust + summon for one issue and, when eligible, apply the decided
 * transition. Returns the outcome; performs NO writes when the issue is held for
 * a maintainer summon. Best-effort gh writes (mirrors the rest of runtime/gh).
 */
export async function runTriage(
  ctx: GhContext,
  policy: TrustPolicy,
  opts: TriageOptions,
): Promise<TriageOutcome> {
  const author = await issueAuthor(ctx, opts.issue);
  const labels = await viewLabels(ctx, opts.issue);
  const summoned = opts.summon || labels.includes(LABEL_TRIAGE_SUMMON);
  const authorTrusted = isAuthorTrusted(policy, author);
  const action = routeNeedsTriage(policy, { authorTrusted, summoned });

  if (action === "hold-for-summon") {
    return {
      issue: opts.issue,
      action,
      author,
      reason: `untrusted author ${author ? `'${author}'` : "(unknown)"} — held for a maintainer summon (\`dev triage --summon\` or the \`${LABEL_TRIAGE_SUMMON}\` label)`,
    };
  }

  const transition = planTriageTransition(opts.decision);
  // Shed the summon label too, if it was the release channel.
  const remove = labels.includes(LABEL_TRIAGE_SUMMON)
    ? [...transition.remove, LABEL_TRIAGE_SUMMON]
    : transition.remove;
  for (const label of transition.add) await ensureLabel(ctx, label);
  await editLabels(ctx, opts.issue, remove, transition.add);
  await comment(
    ctx,
    opts.issue,
    `${TRIAGE_DISCLAIMER}\n\n🤖 \`dev triage\`: ${opts.decision}` +
      (summoned && !authorTrusted ? " (released by maintainer summon)" : "") +
      ".",
  );
  if (transition.close) await closeIssue(ctx, opts.issue);

  return { issue: opts.issue, action, author, applied: { decision: opts.decision, transition } };
}

interface TriageFlags {
  issue: number;
  decision: TriageDecision;
  summon: boolean;
  repo?: string;
  json: boolean;
}

function parseTriageFlags(args: readonly string[]): TriageFlags {
  let issue: number | undefined;
  let decision: TriageDecision | undefined;
  let summon = false;
  let repo: string | undefined;
  let json = false;

  const takeDecision = (value: string | undefined, flag: string): TriageDecision => {
    if (value === undefined) throw new Error(`${flag} requires a value`);
    if (!isTriageDecision(value)) {
      throw new Error(`${flag}: '${value}' is not a triage decision (${TRIAGE_DECISIONS.join(" | ")})`);
    }
    return value;
  };

  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i]!;
    if (arg === "--summon") {
      summon = true;
      continue;
    }
    if (arg === "--json") {
      json = true;
      continue;
    }
    if (arg === "--decision") {
      decision = takeDecision(args[++i], "--decision");
      continue;
    }
    if (arg.startsWith("--decision=")) {
      decision = takeDecision(arg.slice("--decision=".length), "--decision");
      continue;
    }
    if (arg === "--repo" || arg === "-R") {
      const value = args[++i];
      if (value === undefined) throw new Error(`${arg} requires a value`);
      repo = value;
      continue;
    }
    if (arg.startsWith("--repo=")) {
      repo = arg.slice("--repo=".length);
      continue;
    }
    if (arg.startsWith("-")) throw new Error(`unknown flag: ${arg}`);
    // First positional is the issue number (accepts a leading '#').
    const n = Number(arg.replace(/^#/, ""));
    if (!Number.isInteger(n) || n <= 0) throw new Error(`invalid issue number: ${arg}`);
    issue = n;
  }

  if (issue === undefined) throw new Error("usage: dev triage <issue> --decision <state> [--summon]");
  if (decision === undefined) {
    throw new Error(`--decision is required (${TRIAGE_DECISIONS.join(" | ")})`);
  }
  return { issue, decision, summon, repo, json };
}

/**
 * `dev triage <issue> --decision <state> [--summon]` — the trust-gated triage
 * applicator. Loads the per-repo trust allowlist, resolves the issue's author,
 * and either applies the decided transition or holds the issue for a summon.
 */
export async function triageCommand(
  args: string[],
  cwd = process.cwd(),
  stdout: NodeJS.WritableStream = process.stdout,
): Promise<number> {
  let flags: TriageFlags;
  try {
    flags = parseTriageFlags(args);
  } catch (error) {
    stdout.write(`[triage] ${error instanceof Error ? error.message : String(error)}\n`);
    return 2;
  }

  const config = loadConfig(resolveConfigPath(cwd), { warn: () => undefined });
  const policy = parseTrustPolicy(config);
  const repo = flags.repo ?? (await resolveRepoContext(cwd)).repo;
  const ctx: GhContext = { cwd, repo };

  const outcome = await runTriage(ctx, policy, {
    issue: flags.issue,
    decision: flags.decision,
    summon: flags.summon,
  });

  if (flags.json) {
    stdout.write(`${JSON.stringify(outcome)}\n`);
    return 0;
  }

  if (outcome.action === "hold-for-summon") {
    stdout.write(`triage: #${outcome.issue} held — ${outcome.reason}\n`);
    return 0;
  }
  stdout.write(
    `triage: #${outcome.issue} → ${flags.decision}` +
      (outcome.applied?.transition.close ? " (closed)" : "") +
      "\n",
  );
  return 0;
}
