/**
 * generate.ts — the build-time CLI that emits `opencode.json` from a
 * project's `.red/config.yaml` and the ADR 0059 env-precedence rule.
 *
 * Usage (local-dev path):
 *   pnpm --filter @redskills/opencode-host generate
 *   pnpm --filter @redskills/opencode-host generate -- --config ./.red/config.yaml --out ./opencode.json
 *
 * Behaviour:
 *   - reads `<config>` (default `./.red/config.yaml`),
 *   - checks the ADR 0067 strict opt-in gate (`plugins.dev.enabled: true`),
 *   - builds the Slice 1 `opencode.json` payload via {@link buildProviderBlock},
 *   - writes it to `<out>` (default `./opencode.json`) as pretty JSON with a
 *     header comment naming the generator and its version.
 *
 * Exit codes:
 *   0  — wrote the file.
 *   1  — read or write failure, or the opt-in gate is closed.
 *   2  — usage error.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { readBuildInfo, renderVersion } from "@reddb-io/build-info";
import {
  buildProviderBlock,
  isDevPluginEnabled,
  pickAuthPrecedence,
  type OpencodeConfig,
} from "./provider-block.js";

interface CliArgs {
  configPath: string;
  outPath: string;
  showHelp: boolean;
  printJson: boolean;
}

function parseArgs(argv: ReadonlyArray<string>): CliArgs {
  const args: CliArgs = {
    configPath: "./.red/config.yaml",
    outPath: "./opencode.json",
    showHelp: false,
    printJson: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--config" || arg === "-c") {
      const next = argv[++i];
      if (typeof next !== "string" || next.length === 0) {
        process.stderr.write("opencode-host: --config requires a path\n");
        process.exit(2);
      }
      args.configPath = next;
    } else if (arg === "--out" || arg === "-o") {
      const next = argv[++i];
      if (typeof next !== "string" || next.length === 0) {
        process.stderr.write("opencode-host: --out requires a path\n");
        process.exit(2);
      }
      args.outPath = next;
    } else if (arg === "--help" || arg === "-h") {
      args.showHelp = true;
    } else if (arg === "--print") {
      args.printJson = true;
    } else {
      process.stderr.write(`opencode-host: unknown arg ${arg}\n`);
      process.exit(2);
    }
  }
  return args;
}

const HELP = `opencode-host generate — emit opencode.json from .red/config.yaml (Slice 1)

Usage:
  opencode-host generate [--config <path>] [--out <path>] [--print]
  opencode-host generate --help

Options:
  -c, --config <path>   path to .red/config.yaml (default: ./.red/config.yaml)
  -o, --out <path>      path to write opencode.json (default: ./opencode.json)
  --print               print the generated JSON to stdout instead of writing
  -h, --help            show this help

Exit codes:
  0  wrote (or printed) successfully
  1  read/write failure or opt-in gate closed (plugins.dev.enabled: true missing)
  2  usage error
`;

function renderJson(config: OpencodeConfig, buildVersion: string): string {
  const header = [
    "// generated by @redskills/opencode-host",
    `// version: ${buildVersion}`,
    "// slice: 1 (provider block only; skills/hooks/MCP land in slices 2-5)",
    "// do not edit by hand — re-run the generator to refresh.",
    "",
  ].join("\n");
  return header + JSON.stringify(config, null, 2) + "\n";
}

function main(argv: ReadonlyArray<string>): void {
  const args = parseArgs(argv);
  if (args.showHelp) {
    process.stdout.write(HELP);
    return;
  }

  const info = readBuildInfo("opencode-host");
  const buildVersion = renderVersion(info);

  let configText: string;
  try {
    configText = readFileSync(resolve(args.configPath), "utf8");
  } catch (err) {
    process.stderr.write(
      `opencode-host: could not read config at ${args.configPath}: ${(err as Error).message}\n`,
    );
    process.exit(1);
  }

  if (!isDevPluginEnabled(configText)) {
    process.stderr.write(
      "opencode-host: refusing to emit — plugins.dev.enabled is not true in .red/config.yaml (ADR 0067 strict opt-in). Run /setup-red-skills to enable the dev plugin.\n",
    );
    process.exit(1);
  }

  const config = buildProviderBlock({
    configText,
    env: process.env,
  });

  // Fail-closed per ADR 0059: no env precedence slot set means no auth is
  // reachable. The generator still emits the file (so the opencode TUI can
  // show all three providers and the user can `/connect`), but it logs a
  // warning naming the active provider. The /connect flow is the canonical
  // way to populate auth.json in that case.
  const active = pickAuthPrecedence(process.env);
  if (active === undefined) {
    process.stderr.write(
      "opencode-host: no auth env-var set (OPENAI_API_KEY / MINIMAX_API_KEY / OPENROUTER_API_KEY). Run `/connect` inside opencode to pick a provider, or export one of the env vars.\n",
    );
  }

  const rendered = renderJson(config, buildVersion);

  if (args.printJson) {
    process.stdout.write(rendered);
    return;
  }

  const outAbs = resolve(args.outPath);
  try {
    mkdirSync(dirname(outAbs), { recursive: true });
    writeFileSync(outAbs, rendered, "utf8");
  } catch (err) {
    process.stderr.write(
      `opencode-host: could not write ${args.outPath}: ${(err as Error).message}\n`,
    );
    process.exit(1);
  }

  process.stdout.write(
    `opencode-host: wrote ${args.outPath} (provider=${active ?? "openrouter"} via precedence, model=${config.model})\n`,
  );
}

main(process.argv.slice(2));
