export const ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER =
  "<!-- red:acceptance-criteria-lint v1 -->";

const TRIAGE_DISCLAIMER = "> *This was generated by AI during triage.*";

export interface AcceptanceCriteriaLintResult {
  ok: boolean;
  reason: string;
  items: string[];
}

const ACCEPTANCE_HEADING_RE = /^\s*(?:#{1,6}\s+)?acceptance\s+criteria\s*:?\s*$/i;
const BOLD_ACCEPTANCE_HEADING_RE = /^\s*\*\*acceptance\s+criteria:?\*\*\s*$/i;
const NEXT_SECTION_RE = /^\s*(?:#{1,6}\s+\S|\*\*[^*]+:?\*\*\s*$)/;
const CHECKLIST_ITEM_RE = /^\s*(?:[-*+]|\d+[.)])\s+(?:\[[ xX]\]\s*)?(.+?)\s*$/;

const CHECKABLE_PATTERNS = [
  /`[^`]+`/,
  /\b(?:pnpm|npm|yarn|bun|cargo|go test|pytest|vitest|jest|playwright|make|gh|curl)\b/i,
  /\b(?:test|tests|fixture|fixtures|snapshot|assert|expect|regression)\b/i,
  /\b(?:running|run|returns?|exits?|emits?|prints?|contains?|renders?|creates?|updates?|removes?|routes?|labels?|stays?|fails?|passes?|blocks?|allows?|rejects?)\b/i,
  /\b(?:idempotent|exactly one|no duplicate|machine-checkable)\b/i,
];

export function lintExecutableAcceptanceCriteria(body: string): AcceptanceCriteriaLintResult {
  const section = acceptanceCriteriaSection(body);
  if (section === undefined) {
    return { ok: false, reason: "missing acceptance-criteria section", items: [] };
  }

  const items = extractChecklistItems(section);
  if (items.length === 0) {
    return { ok: false, reason: "acceptance-criteria section has no checklist items", items };
  }

  for (const item of items) {
    if (!isMachineCheckable(item)) {
      return {
        ok: false,
        reason: `acceptance criteria item is not machine-checkable: ${item}`,
        items,
      };
    }
  }

  return { ok: true, reason: "ok", items };
}

export function renderAcceptanceCriteriaRecipeComment(result: AcceptanceCriteriaLintResult): string {
  return [
    TRIAGE_DISCLAIMER,
    "",
    ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER,
    "",
    "`dev triage` kept this issue in `needs-triage` because it is not yet safe for `ready-for-agent`.",
    "",
    `Missing: ${result.reason}.`,
    "",
    "Add a machine-checkable acceptance criteria section. Each item should name a verifiable artifact: a test, command, fixture, or pinned observable behavior.",
    "",
    "Template:",
    "",
    "```markdown",
    "## Acceptance criteria",
    "",
    "- [ ] Running `pnpm --filter @reddb-io/dev test -- <focused-test>` passes.",
    "- [ ] The failing fixture demonstrates the behavior before the fix.",
    "- [ ] Re-running the command leaves the same observable state, with no duplicate comments or labels.",
    "```",
  ].join("\n");
}

export function hasAcceptanceCriteriaRecipeComment(comments: readonly { body: string }[]): boolean {
  return comments.some((comment) => comment.body.includes(ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER));
}

function acceptanceCriteriaSection(body: string): string | undefined {
  const lines = body.split(/\r?\n/);
  const start = lines.findIndex((line) => ACCEPTANCE_HEADING_RE.test(line) || BOLD_ACCEPTANCE_HEADING_RE.test(line));
  if (start < 0) return undefined;
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((line) => NEXT_SECTION_RE.test(line));
  return (end < 0 ? rest : rest.slice(0, end)).join("\n");
}

function extractChecklistItems(section: string): string[] {
  return section
    .split(/\r?\n/)
    .map((line) => CHECKLIST_ITEM_RE.exec(line)?.[1]?.trim())
    .filter((item): item is string => Boolean(item));
}

function isMachineCheckable(item: string): boolean {
  return CHECKABLE_PATTERNS.some((pattern) => pattern.test(item));
}
