export const copy = {
  app: {
    eyebrow: "REDSKILLS",
    title: "redskilled",
    subtitle: "Mobile operator",
    platform: "ANDROID",
    loading: "Loading the mobile operator",
  },
  host: {
    section: "HOST",
    emptyTitle: "Pair this device",
    emptyDescription:
      "Scan or paste the one-use invitation generated by the Remote link on your Host.",
    scanAction: "SCAN QR CODE",
    cameraLoading: "Checking camera access...",
    cameraPermission: "Camera access is used only while scanning a Host pairing QR code.",
    cameraAllow: "ALLOW CAMERA",
    cameraUnavailable: "Camera access is blocked. Enable it in system settings or paste the invitation below.",
    cameraCancel: "CANCEL SCAN",
    cameraHint: "Point the camera at the pairing QR shown on your Host.",
    cameraLabel: "Host pairing QR scanner",
    invitationLabel: "Host pairing invitation",
    invitationPlaceholder: "Paste the pairing invitation",
    pairAction: "PAIR HOST",
    paired: "PAIRED",
    pairedDescription: "Encrypted link · paired device",
  },
  dispatch: {
    section: "DISPATCH",
    title: "Start from a GitHub Issue",
    description:
      "Your Host resolves the repository, provisions the Project, and starts one Worker.",
    issueLabel: "GitHub Issue URL",
    issuePlaceholder: "https://github.com/owner/repo/issues/123",
    invalidIssue: "Enter a URL like https://github.com/owner/repo/issues/123",
    action: "DISPATCH WORKER",
  },
  workers: {
    section: "WORKERS",
    count: (count: number) => `${count} ACTIVE`,
    emptyTitle: "No active Workers",
    emptyDescription:
      "A dispatched Worker will appear here with its repository and Ticket.",
    running: "RUNNING",
    stop: "STOP",
  },
  errors: {
    pairing: "The Host refused this pairing invitation.",
    dispatch: "The Host refused this Ticket dispatch.",
    stop: "The Host refused to stop this Worker.",
  },
} as const;
