export const ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER =
  "<!-- red:acceptance-criteria-lint v1 -->";

const TRIAGE_DISCLAIMER = "> *This was generated by AI during triage.*";

export interface AcceptanceCriteriaLintResult {
  ok: boolean;
  reason: string;
  items: string[];
}

const ACCEPTANCE_HEADING_RE = /^\s*(?:#{1,6}\s+)?acceptance\s+criteria\s*:?\s*$/i;
const BOLD_ACCEPTANCE_HEADING_RE = /^\s*\*\*acceptance\s+criteria:?\*\*\s*$/i;
const NEXT_SECTION_RE = /^\s*(?:#{1,6}\s+\S|\*\*[^*]+:?\*\*\s*$)/;
const CHECKLIST_ITEM_RE = /^\s*(?:[-*+]|\d+[.)])\s+(?:\[[ xX]\]\s*)?(.+?)\s*$/;

const DIRECT_ARTIFACT_PATTERNS = [
  /`[^`]+`/,
  /\b(?:pnpm|npm|yarn|bun|cargo|go test|pytest|vitest|jest|playwright|make|gh|curl)\b/i,
  /\b(?:test|tests|fixture|fixtures|snapshot|assert|expect|regression|reproduction|command|workflow)\b/i,
];

const OBSERVABLE_SURFACE_RE =
  /\b(?:artifact|behavior|body|branch|comment|exit code|field|file|issue|label|output|pr|request|response|route|state|status|stderr|stdout|url|workflow)\b/i;

const PINNED_BEHAVIOR_RE =
  /\b(?:at least|at most|blocks?|contains?|does not|emits?|equals?|exactly|exits?|fails?|idempotent|leaves?|machine-checkable|no duplicate|only one|prints?|receives?|rejects?|remains?|returns?|routes?|same observable|stays?|without|with no)\b/i;

const TRUSTED_RECIPE_COMMENT_SOURCES = new Set(["automation", "trusted"]);

export interface AcceptanceCriteriaRecipeComment {
  id?: number;
  body: string;
  sourceTrust?: string;
}

export interface OwnedAcceptanceCriteriaRecipeComment {
  id?: number;
  body: string;
}

export interface AcceptanceCriteriaRecipeCommentUpdate {
  action: "none" | "create" | "update";
  id?: number;
  body: string;
}

export function lintExecutableAcceptanceCriteria(body: string): AcceptanceCriteriaLintResult {
  const section = acceptanceCriteriaSection(body);
  if (section === undefined) {
    return { ok: false, reason: "missing acceptance-criteria section", items: [] };
  }

  const items = extractChecklistItems(section);
  if (items.length === 0) {
    return { ok: false, reason: "acceptance-criteria section has no checklist items", items };
  }

  for (const item of items) {
    if (!isMachineCheckable(item)) {
      return {
        ok: false,
        reason: `acceptance criteria item is not machine-checkable: ${item}`,
        items,
      };
    }
  }

  return { ok: true, reason: "ok", items };
}

export function renderAcceptanceCriteriaRecipeComment(result: AcceptanceCriteriaLintResult): string {
  return [
    TRIAGE_DISCLAIMER,
    "",
    ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER,
    "",
    "`dev triage` kept this issue in `needs-triage` because it is not yet safe for `ready-for-agent`.",
    "",
    `Missing: ${result.reason}.`,
    "",
    "Add a machine-checkable acceptance criteria section. Each item should name a verifiable artifact: a test, command, fixture, or pinned observable behavior.",
    "",
    "Template:",
    "",
    "```markdown",
    "## Acceptance criteria",
    "",
    "- [ ] Running `pnpm --filter @reddb-io/dev test -- <focused-test>` passes.",
    "- [ ] The failing fixture demonstrates the behavior before the fix.",
    "- [ ] Re-running the command leaves the same observable state, with no duplicate comments or labels.",
    "```",
  ].join("\n");
}

export function hasAcceptanceCriteriaRecipeComment(comments: readonly { body: string }[]): boolean {
  return comments.some((comment) => comment.body.includes(ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER));
}

export function findOwnedAcceptanceCriteriaRecipeComment(
  comments: readonly AcceptanceCriteriaRecipeComment[],
): OwnedAcceptanceCriteriaRecipeComment | undefined {
  return comments.find((comment) => {
    if (!comment.body.includes(ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER)) return false;
    return TRUSTED_RECIPE_COMMENT_SOURCES.has(String(comment.sourceTrust ?? ""));
  });
}

export function planAcceptanceCriteriaRecipeCommentUpdate(
  comments: readonly AcceptanceCriteriaRecipeComment[],
  lint: AcceptanceCriteriaLintResult,
): AcceptanceCriteriaRecipeCommentUpdate {
  const body = renderAcceptanceCriteriaRecipeComment(lint);
  const existing = findOwnedAcceptanceCriteriaRecipeComment(comments);
  if (!existing) return { action: "create", body };
  if (existing.body === body) return { action: "none", id: existing.id, body };
  return { action: "update", id: existing.id, body };
}

function acceptanceCriteriaSection(body: string): string | undefined {
  const lines = body.split(/\r?\n/);
  const start = lines.findIndex((line) => ACCEPTANCE_HEADING_RE.test(line) || BOLD_ACCEPTANCE_HEADING_RE.test(line));
  if (start < 0) return undefined;
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((line) => NEXT_SECTION_RE.test(line));
  return (end < 0 ? rest : rest.slice(0, end)).join("\n");
}

function extractChecklistItems(section: string): string[] {
  return section
    .split(/\r?\n/)
    .map((line) => CHECKLIST_ITEM_RE.exec(line)?.[1]?.trim())
    .filter((item): item is string => Boolean(item));
}

function isMachineCheckable(item: string): boolean {
  if (DIRECT_ARTIFACT_PATTERNS.some((pattern) => pattern.test(item))) return true;
  return OBSERVABLE_SURFACE_RE.test(item) && PINNED_BEHAVIOR_RE.test(item);
}
