#!/usr/bin/env node
// ADR 0040: the version is a single source written by ONE script.
//
// `changeset version` owns the workspace packages in the `fixed` group
// (.changeset/config.json). It does NOT know about the files outside the pnpm
// workspace that carry the same number: the root package.json, the Claude and
// Codex plugin manifests, the in-repo Pi package manifests, and the staged Pi
// packages. This script propagates the changesets-decided version to all of
// them, and `--check` fails when any of them drifts.
//
// Usage:
//   node scripts/sync-version.mjs            # write
//   node scripts/sync-version.mjs --check    # verify only, exit 1 on drift
//   node scripts/sync-version.mjs --version 2.78.0
//
// The source of truth is apps/dev/package.json — a `fixed`-group member, so
// changesets has already written the release version there by the time
// `pnpm release:version` calls this.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// The version anchor changesets writes first; everything below follows it.
const SOURCE = "apps/dev/package.json";

// package.json files outside the `fixed` group (or outside the pnpm workspace)
// that must carry the product version.
//
// `plugins/*` are Pi packages, not pnpm workspace members, so changesets never
// sees them. The VS Code extension IS a workspace member and IS in the fixed
// group; it is named here anyway because its `version` is the field the
// marketplace and the .vsix show, and a surface that visible deserves to be
// covered by the `--check` gate rather than by one mechanism alone (issue #3082).
const PACKAGE_JSONS = [
  "package.json",
  "plugins/dev/package.json",
  "plugins/memory/package.json",
  "plugins/brain/package.json",
  "plugins/internal/package.json",
  "apps/vscode-extension-red-skills/package.json",
];

// Plugin manifests. validate-install-metadata.sh rejects a Claude/Codex pair
// that disagrees, so both sides are written together and checked together.
const PLUGIN_MANIFESTS = [
  "plugins/dev/.claude-plugin/plugin.json",
  "plugins/dev/.codex-plugin/plugin.json",
  "plugins/dev/.gemini-plugin/plugin.json",
  "plugins/memory/.claude-plugin/plugin.json",
  "plugins/memory/.codex-plugin/plugin.json",
  "plugins/memory/.gemini-plugin/plugin.json",
  "plugins/brain/.claude-plugin/plugin.json",
  "plugins/brain/.codex-plugin/plugin.json",
  "plugins/brain/.gemini-plugin/plugin.json",
  "plugins/internal/.claude-plugin/plugin.json",
  "plugins/internal/.codex-plugin/plugin.json",
  "plugins/internal/.gemini-plugin/plugin.json",
];

// Staged Pi packages are regenerated by `pnpm pi:packages:build`, but they are
// committed, so keep them coherent when they exist.
const STAGED_PI = [
  "packaging/pi/dev/package.json",
  "packaging/pi/memory/package.json",
  "packaging/pi/brain/package.json",
  "packaging/pi/internal/package.json",
];

// Version-bearing sites that are NOT JSON. Each names the single line it owns,
// so the write is a one-line diff in a file whose format this script has no
// business rewriting.
//
// The herdr plugin carries its version three times — in its package.json (the
// fixed group writes that), in the manifest herdr installs by, and in the
// entry's fallback constant for an unstamped checkout run. Its own
// check-manifest.py already refuses a constant that disagrees with the manifest;
// what nothing checked was either of them against the product version, which is
// how the plugin sat at 0.1.x through every release (issue #3082).
const TEXT_SITES = [
  {
    file: "apps/herdr-plugin-red-skills/herdr-plugin.toml",
    pattern: /^version = "([^"]+)"$/m,
    render: (version) => `version = "${version}"`,
  },
  {
    file: "apps/herdr-plugin-red-skills/bin/red-skills-herdr.mjs",
    pattern: /^const CHECKOUT_VERSION = "([^"]+)";$/m,
    render: (version) => `const CHECKOUT_VERSION = "${version}";`,
  },
];

const JSON_SITES = [...PACKAGE_JSONS, ...PLUGIN_MANIFESTS, ...STAGED_PI].map((file) => ({ file }));

/** Every file this script writes, JSON and not, in write order. */
const VERSION_SITES = [...JSON_SITES, ...TEXT_SITES];

export const VERSION_BEARING_FILES = VERSION_SITES.map((site) => site.file);

function siteFor(relative) {
  const site = VERSION_SITES.find((candidate) => candidate.file === relative);
  if (!site) throw new Error(`no version site declared for ${relative}`);
  return site;
}

function readJson(relative) {
  return JSON.parse(readFileSync(resolve(ROOT, relative), "utf8"));
}

/** The version a site currently carries, or null when its line is missing. */
function readSiteVersion(relative) {
  const site = siteFor(relative);
  if (!site.pattern) return readJson(relative).version;
  const match = site.pattern.exec(readFileSync(resolve(ROOT, relative), "utf8"));
  return match ? match[1] : null;
}

function writeVersion(relative, version) {
  const site = siteFor(relative);
  const absolute = resolve(ROOT, relative);
  const raw = readFileSync(absolute, "utf8");
  if (site.pattern) {
    if (!site.pattern.test(raw)) {
      throw new Error(`${relative} carries no version line matching ${site.pattern}`);
    }
    const next = raw.replace(site.pattern, site.render(version));
    if (next === raw) return false;
    writeFileSync(absolute, next);
    return true;
  }
  const json = JSON.parse(raw);
  if (json.version === version) return false;
  json.version = version;
  // Preserve the two-space + trailing-newline shape every manifest here uses,
  // so a sync that changes nothing else produces a one-line diff.
  writeFileSync(absolute, `${JSON.stringify(json, null, 2)}\n`);
  return true;
}

function parseArgs(argv) {
  const args = { check: false, version: null };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--check") args.check = true;
    else if (argv[i] === "--version") args.version = argv[++i];
    else if (argv[i].startsWith("--version=")) args.version = argv[i].slice("--version=".length);
    else throw new Error(`unknown argument: ${argv[i]}`);
  }
  return args;
}

export function run(argv = []) {
  const { check, version: override } = parseArgs(argv);
  const version = (override ?? readJson(SOURCE).version)?.replace(/^v/, "");
  if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version ?? "")) {
    throw new Error(`invalid version resolved from ${override ? "--version" : SOURCE}: ${version}`);
  }

  const present = VERSION_BEARING_FILES.filter((file) => existsSync(resolve(ROOT, file)));
  const drifted = present.filter((file) => readSiteVersion(file) !== version);

  if (check) {
    if (drifted.length === 0) {
      console.log(`version sync ok — every version-bearing file is at ${version}`);
      return 0;
    }
    for (const file of drifted) {
      console.error(`::error file=${file}::${file} is at ${readSiteVersion(file) ?? "(no version line)"}, expected ${version} (run \`pnpm version:sync\`)`);
    }
    return 1;
  }

  const written = present.filter((file) => writeVersion(file, version));
  if (written.length === 0) console.log(`version sync: already at ${version}`);
  else console.log(`version sync: wrote ${version} to ${written.length} file(s)\n  ${written.join("\n  ")}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    process.exit(run(process.argv.slice(2)));
  } catch (error) {
    console.error(`::error::${error.message}`);
    process.exit(1);
  }
}
