#!/usr/bin/env node
// ADR 0040: the version is a single source written by ONE script.
//
// `changeset version` owns the workspace packages in the `fixed` group
// (.changeset/config.json). It does NOT know about the files outside the pnpm
// workspace that carry the same number: the root package.json, the Claude and
// Codex plugin manifests, the in-repo Pi package manifests, and the staged Pi
// packages. This script propagates the changesets-decided version to all of
// them, and `--check` fails when any of them drifts.
//
// Usage:
//   node scripts/sync-version.mjs            # write
//   node scripts/sync-version.mjs --check    # verify only, exit 1 on drift
//   node scripts/sync-version.mjs --version 2.78.0
//
// The source of truth is apps/dev/package.json — a `fixed`-group member, so
// changesets has already written the release version there by the time
// `pnpm release:version` calls this.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// The version anchor changesets writes first; everything below follows it.
const SOURCE = "apps/dev/package.json";

// package.json files outside the `fixed` group (or outside the pnpm workspace)
// that must carry the product version.
const PACKAGE_JSONS = [
  "package.json",
  "plugins/dev/package.json",
  "plugins/memory/package.json",
  "plugins/brain/package.json",
];

// Plugin manifests. validate-install-metadata.sh rejects a Claude/Codex pair
// that disagrees, so both sides are written together and checked together.
const PLUGIN_MANIFESTS = [
  "plugins/dev/.claude-plugin/plugin.json",
  "plugins/dev/.codex-plugin/plugin.json",
  "plugins/dev/.gemini-plugin/plugin.json",
  "plugins/memory/.claude-plugin/plugin.json",
  "plugins/memory/.codex-plugin/plugin.json",
  "plugins/memory/.gemini-plugin/plugin.json",
  "plugins/brain/.claude-plugin/plugin.json",
  "plugins/brain/.codex-plugin/plugin.json",
  "plugins/brain/.gemini-plugin/plugin.json",
];

// Staged Pi packages are regenerated by `pnpm pi:packages:build`, but they are
// committed, so keep them coherent when they exist.
const STAGED_PI = [
  "packaging/pi/dev/package.json",
  "packaging/pi/memory/package.json",
  "packaging/pi/brain/package.json",
];

export const VERSION_BEARING_FILES = [
  ...PACKAGE_JSONS,
  ...PLUGIN_MANIFESTS,
  ...STAGED_PI,
];

function readJson(relative) {
  return JSON.parse(readFileSync(resolve(ROOT, relative), "utf8"));
}

function writeVersion(relative, version) {
  const absolute = resolve(ROOT, relative);
  const raw = readFileSync(absolute, "utf8");
  const json = JSON.parse(raw);
  if (json.version === version) return false;
  json.version = version;
  // Preserve the two-space + trailing-newline shape every manifest here uses,
  // so a sync that changes nothing else produces a one-line diff.
  writeFileSync(absolute, `${JSON.stringify(json, null, 2)}\n`);
  return true;
}

function parseArgs(argv) {
  const args = { check: false, version: null };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--check") args.check = true;
    else if (argv[i] === "--version") args.version = argv[++i];
    else if (argv[i].startsWith("--version=")) args.version = argv[i].slice("--version=".length);
    else throw new Error(`unknown argument: ${argv[i]}`);
  }
  return args;
}

export function run(argv = []) {
  const { check, version: override } = parseArgs(argv);
  const version = (override ?? readJson(SOURCE).version)?.replace(/^v/, "");
  if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version ?? "")) {
    throw new Error(`invalid version resolved from ${override ? "--version" : SOURCE}: ${version}`);
  }

  const present = VERSION_BEARING_FILES.filter((file) => existsSync(resolve(ROOT, file)));
  const drifted = present.filter((file) => readJson(file).version !== version);

  if (check) {
    if (drifted.length === 0) {
      console.log(`version sync ok — every version-bearing file is at ${version}`);
      return 0;
    }
    for (const file of drifted) {
      console.error(`::error file=${file}::${file} is at ${readJson(file).version}, expected ${version} (run \`pnpm version:sync\`)`);
    }
    return 1;
  }

  const written = present.filter((file) => writeVersion(file, version));
  if (written.length === 0) console.log(`version sync: already at ${version}`);
  else console.log(`version sync: wrote ${version} to ${written.length} file(s)\n  ${written.join("\n  ")}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    process.exit(run(process.argv.slice(2)));
  } catch (error) {
    console.error(`::error::${error.message}`);
    process.exit(1);
  }
}
