#!/usr/bin/env node
import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);
import{spawnSync as L}from"node:child_process";import{createHash as U}from"node:crypto";import{existsSync as m,readFileSync as N}from"node:fs";import{appendFile as T,mkdir as k,readFile as H,writeFile as j}from"node:fs/promises";import{homedir as M}from"node:os";import{dirname as w,join as u}from"node:path";import{fileURLToPath as G}from"node:url";var c=class extends Error{kind;cause;constructor(n,t,r){super(t),this.name="BundleFetchError",this.kind=n,this.cause=r}};function h(e,n){return`${e}-${n}.bundle.min.mjs`}function d(e){let{plugin:n,version:t,cacheDir:r}=e;return C(r,h(n,t))}function v(e,n,t){return`https://github.com/${e}/releases/download/v${n}/${t}`}function O(e){return`${e}.bundle.min.mjs`}function I(e){return`${e}.manifest.json`}async function g(e,n){let{plugin:t,version:r,repo:i,cacheDir:o}=n,s=d({plugin:t,version:r,cacheDir:o}),a=await A(e,i,t,r);if(await e.exists(s))try{if(e.sha256(await e.readFile(s))===a.sha256.toLowerCase())return s}catch{}let l=O(t),f;try{f=await e.download(v(i,r,l))}catch($){throw b($,l)}let y=e.sha256(f);if(y!==a.sha256.toLowerCase())throw new c("checksum-mismatch",`checksum mismatch for ${l}: ${y} != ${a.sha256}`);return await e.writeFile(s,f),s}async function A(e,n,t,r){let i=I(t),o;try{o=await e.download(v(n,r,i))}catch(a){throw b(a,i)}let s;try{s=JSON.parse(new TextDecoder().decode(o))}catch(a){throw new c("manifest-invalid",`manifest ${i} is not valid JSON`,a)}if(!S(s))throw new c("manifest-invalid",`manifest ${i} missing required fields {plugin, version, sha256}`);return{...s,sha256:s.sha256.toLowerCase()}}function S(e){if(typeof e!="object"||e===null)return!1;let n=e;return typeof n.plugin=="string"&&typeof n.version=="string"&&typeof n.sha256=="string"&&/^[0-9a-f]{64}$/i.test(n.sha256)}function b(e,n){let t=e instanceof Error?e.message:String(e);return/\b404\b|not found|missing/i.test(t)?new c("asset-missing",`release asset ${n} not found: ${t}`,e):new c("network",`failed to download ${n}: ${t}`,e)}function C(e,n){return e.endsWith("/")?`${e}${n}`:`${e}/${n}`}var p="reddb-io/red-skills";function J(){try{return"fetch"}catch{return""}}function F(e){return e||(process.env.RED_SKILLS_CACHE_DIR?process.env.RED_SKILLS_CACHE_DIR:process.env.XDG_CACHE_HOME?u(process.env.XDG_CACHE_HOME,"red-skills","bundles"):u(M(),".cache","red-skills","bundles"))}var _={async download(e){let n=await fetch(e,{redirect:"follow"});if(!n.ok)throw new Error(`GET ${e} -> ${n.status}`);return new Uint8Array(await n.arrayBuffer())},async readFile(e){return new Uint8Array(await H(e))},async writeFile(e,n){await k(w(e),{recursive:!0}),await j(e,n)},async exists(e){return m(e)},sha256(e){return U("sha256").update(e).digest("hex")}};async function B(e,n){try{await k(e,{recursive:!0}),await T(u(e,"red-fetch.log"),`[${new Date().toISOString()}] ${n}
`)}catch{}process.stderr.write(`entrypoint: ${n}
`)}function x(e){let n={mode:"fetch",repo:p,help:!1},t=[];for(let r=0;r<e.length;r++){let i=e[r];i==="--help"||i==="-h"?n.help=!0:i==="--repo"?n.repo=e[++r]??n.repo:i==="--cache-dir"?n.cacheDir=e[++r]:i.startsWith("-")||t.push(i)}return n.plugin=t[0],n.version=t[1],n}function W(e,n){return n.startsWith("run:")?{mode:"run",plugin:n.slice(4),rest:[...e],repo:p}:e[0]==="run"?{mode:"run",plugin:e[1],rest:e.slice(2),repo:p}:e[0]==="fetch"?x(e.slice(1)):x(e)}var R=(()=>{try{return w(G(import.meta.url))}catch{return process.cwd()}})();function D(e,n){let t=e;for(let r=0;r<16;r++){let i=u(t,n);if(m(i))return i;let o=w(t);if(o===t)break;t=o}return null}function Y(){let e=D(R,u(".claude-plugin","plugin.json"));if(!e)return"";try{return JSON.parse(N(e,"utf8")).version||""}catch{return""}}function E(e,n,t){if(!n)return null;let r=d({plugin:e,version:n,cacheDir:t});return m(r)?r:null}function P(e){return D(R,u("dist",`${e}.bundle.min.mjs`))}async function q(e){let{plugin:n}=e;n||(process.stderr.write("entrypoint: `run` requires a <plugin> name.\n"),process.exit(1));let t=F(e.cacheDir),r=Y(),i=E(n,r,t)??P(n);if(!i&&r)try{i=await g(_,{plugin:n,version:r,repo:e.repo,cacheDir:t})}catch(s){let a=s instanceof c?s.kind:"unknown",l=s instanceof Error?s.message:String(s);await B(t,`${a}: ${l} (run plugin=${n} version=${r})`),i=E(n,r,t)??P(n)}if(!i){let s=r?h(n,r):`${n}-<version>.bundle.min.mjs`;process.stderr.write(`entrypoint: could not resolve the ${n} runtime bundle (${s}).
  Looked in cache ${t} and repo-root dist/.
  The bundle ships as a GitHub Release asset (ADR 0034) fetched by red-fetch;
  ensure network access on first run, or build it locally:
    pnpm -C apps/${n} run bundle
`),process.exit(1)}let o=L(process.execPath,[i,...e.rest],{stdio:"inherit"});o.signal&&process.kill(process.pid,o.signal),process.exit(o.status??1)}var K=`entrypoint (fetch) \u2014 resolve a plugin's built bundle from its GitHub Release into a local cache.

Usage:
  node <entrypoint> fetch <plugin> <version> [--repo owner/name] [--cache-dir DIR]
  node red-fetch.mjs       <plugin> <version> [--repo owner/name] [--cache-dir DIR]

Arguments:
  <plugin>     plugin name (e.g. dev, memory)
  <version>    plugin version without the leading v (e.g. 1.140.0)

Options:
  --repo       GitHub repo publishing the release (default: ${p})
  --cache-dir  override the bundle cache dir
  -h, --help   show this help

Best-effort: never blocks session start. On any failure it logs to
<cache-dir>/red-fetch.log and exits 0.`;async function X(e){let n=F(e.cacheDir);(e.help||!e.plugin||!e.version)&&(process.stdout.write(`${K}
`),!e.help&&(!e.plugin||!e.version)&&process.stdout.write(`
entrypoint: missing <plugin> and/or <version>; nothing to do.
`),process.exit(0));let{plugin:t,version:r}=e,i=d({plugin:t,version:r,cacheDir:n});try{let o=await g(_,{plugin:t,version:r,repo:e.repo,cacheDir:n});process.stdout.write(`entrypoint: bundle ready at ${o}
`)}catch(o){let s=o instanceof c?o.kind:"unknown",a=o instanceof Error?o.message:String(o);await B(n,`${s}: ${a} (fetch plugin=${t} version=${r})`),process.stdout.write(`entrypoint: could not fetch ${t}@${r} (${s}); expected cache path ${i}. Continuing \u2014 fetch is best-effort.
`)}process.exit(0)}async function V(){let e=W(process.argv.slice(2),J());e.mode==="run"?await q(e):await X(e)}import.meta.url===`file://${process.argv[1]}`&&V();export{W as parseEntrypoint};
