#!/usr/bin/env node
import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);
import{spawnSync as te}from"node:child_process";import{createHash as re}from"node:crypto";import{existsSync as B,readFileSync as L}from"node:fs";import{appendFile as ie,mkdir as O,readFile as se,writeFile as oe}from"node:fs/promises";import{homedir as ae}from"node:os";import{dirname as I,join as d}from"node:path";import{fileURLToPath as ce}from"node:url";var M=["stable","canary"],V="stable",G="RED_SKILLS_CHANNEL",W="canary";function C(e){if(typeof e!="string")return null;let n=e.trim().toLowerCase();return M.includes(n)?n:null}function E(e={}){let n=C(e.env?.[G]);if(n)return n;let t=C(e.configValue);return t||V}function g(e,n){return e==="canary"?W:`v${n}`}var c=class extends Error{kind;cause;constructor(n,t,i){super(t),this.name="BundleFetchError",this.kind=n,this.cause=i}};function $(e,n,t="stable"){return`${e}-${t==="canary"?"canary":n}.bundle.min.mjs`}function m(e){let{plugin:n,version:t,cacheDir:i,channel:r}=e;return X(i,$(n,t,r))}function k(e,n,t){return`https://github.com/${e}/releases/download/${n}/${t}`}function Y(e){return`${e}.bundle.min.mjs`}function J(e){return`${e}.manifest.json`}async function v(e,n){let{plugin:t,version:i,repo:r,cacheDir:a,channel:s="stable"}=n,o=m({plugin:t,version:i,cacheDir:a,channel:s}),l=g(s,i),u=await K(e,r,t,l);if(await e.exists(o))try{if(e.sha256(await e.readFile(o))===u.sha256.toLowerCase())return o}catch{}let h=Y(t),f;try{f=await e.download(k(r,l,h))}catch(x){throw _(x,h)}let b=e.sha256(f);if(b!==u.sha256.toLowerCase())throw new c("checksum-mismatch",`checksum mismatch for ${h}: ${b} != ${u.sha256}`);return await e.writeFile(o,f),o}async function K(e,n,t,i){let r=J(t),a;try{a=await e.download(k(n,i,r))}catch(o){throw _(o,r)}let s;try{s=JSON.parse(new TextDecoder().decode(a))}catch(o){throw new c("manifest-invalid",`manifest ${r} is not valid JSON`,o)}if(!q(s))throw new c("manifest-invalid",`manifest ${r} missing required fields {plugin, version, sha256}`);return{...s,sha256:s.sha256.toLowerCase()}}function q(e){if(typeof e!="object"||e===null)return!1;let n=e;return typeof n.plugin=="string"&&typeof n.version=="string"&&typeof n.sha256=="string"&&/^[0-9a-f]{64}$/i.test(n.sha256)}function _(e,n){let t=e instanceof Error?e.message:String(e);return/\b404\b|not found|missing/i.test(t)?new c("asset-missing",`release asset ${n} not found: ${t}`,e):new c("network",`failed to download ${n}: ${t}`,e)}function X(e,n){return e.endsWith("/")?`${e}${n}`:`${e}/${n}`}import{existsSync as z,readFileSync as Q}from"node:fs";import{dirname as Z,join as P}from"node:path";function p(e,n){let t=e;for(let i=0;i<16;i++){let r=P(t,n);if(z(r))return r;let a=Z(t);if(a===t)break;t=a}return null}function ee(e){let n=e.indexOf(" #");return(n>=0?e.slice(0,n):e).trim()}function y(e,n){let t=[];for(let i of e.split(`
`)){let r=i.replace(/\r$/,""),a=r.trim();if(!a||a.startsWith("#"))continue;let s=r.indexOf(":");if(s<0)continue;let o=r.length-r.trimStart().length,l=r.slice(0,s).trim();if(!l)continue;let u=r.slice(s+1).trim();for(;t.length&&t[t.length-1].indent>=o;)t.pop();if(t.push({indent:o,key:l}),u&&t.map(f=>f.key).join(".")===n)return ee(u)}}function ne(e,n){return y(e,`plugins.${n}.enabled`)==="true"}function R(e,n){let t=p(e,P(".red","config.yaml"));if(!t)return!1;let i;try{i=Q(t,"utf8")}catch{return!1}return ne(i,n)}var w="reddb-io/red-skills";function le(){try{return"fetch"}catch{return""}}function N(e){return e||(process.env.RED_SKILLS_CACHE_DIR?process.env.RED_SKILLS_CACHE_DIR:process.env.XDG_CACHE_HOME?d(process.env.XDG_CACHE_HOME,"red-skills","bundles"):d(ae(),".cache","red-skills","bundles"))}var S={async download(e){let n=await fetch(e,{redirect:"follow"});if(!n.ok)throw new Error(`GET ${e} -> ${n.status}`);return new Uint8Array(await n.arrayBuffer())},async readFile(e){return new Uint8Array(await se(e))},async writeFile(e,n){await O(I(e),{recursive:!0}),await oe(e,n)},async exists(e){return B(e)},sha256(e){return re("sha256").update(e).digest("hex")}};async function U(e,n){try{await O(e,{recursive:!0}),await ie(d(e,"red-fetch.log"),`[${new Date().toISOString()}] ${n}
`)}catch{}process.stderr.write(`entrypoint: ${n}
`)}function F(e){let n={mode:"fetch",repo:w,help:!1},t=[];for(let i=0;i<e.length;i++){let r=e[i];r==="--help"||r==="-h"?n.help=!0:r==="--repo"?n.repo=e[++i]??n.repo:r==="--cache-dir"?n.cacheDir=e[++i]:r.startsWith("-")||t.push(r)}return n.plugin=t[0],n.version=t[1],n}function ue(e,n){return n.startsWith("run:")?{mode:"run",plugin:n.slice(4),rest:[...e],repo:w}:e[0]==="run"?{mode:"run",plugin:e[1],rest:e.slice(2),repo:w}:e[0]==="fetch"?F(e.slice(1)):F(e)}function de(e){return y(e,"plugins.dev.afk.release.channel")??y(e,"afk.release.channel")}function H(e,n){return E({env:e,configValue:n?de(n):void 0})}function j(){let e=p(process.cwd(),d(".red","config.yaml"));if(e)try{return L(e,"utf8")}catch{return}}var T=(()=>{try{return I(ce(import.meta.url))}catch{return process.cwd()}})();function fe(){let e=p(T,d(".claude-plugin","plugin.json"));if(!e)return"";try{return JSON.parse(L(e,"utf8")).version||""}catch{return""}}function A(e,n,t,i){if(!n&&i!=="canary")return null;let r=m({plugin:e,version:n,cacheDir:t,channel:i});return B(r)?r:null}function D(e){return p(T,d("dist",`${e}.bundle.min.mjs`))}async function pe(e){let{plugin:n}=e;n||(process.stderr.write("entrypoint: `run` requires a <plugin> name.\n"),process.exit(1)),R(process.cwd(),n)||(process.stderr.write(`entrypoint: ${n} is not enabled in this directory (no \`plugins.${n}.enabled: true\` in .red/config.yaml). Run /setup-red-skills to enable it.
`),process.exit(0));let t=N(e.cacheDir),i=fe(),r=H(process.env,j());process.stderr.write(`entrypoint: resolving ${n} via ${r} channel (${g(r,i)})
`);let a=A(n,i,t,r)??D(n);if(!a&&(i||r==="canary"))try{a=await v(S,{plugin:n,version:i,repo:e.repo,cacheDir:t,channel:r})}catch(o){let l=o instanceof c?o.kind:"unknown",u=o instanceof Error?o.message:String(o);await U(t,`${l}: ${u} (run plugin=${n} version=${i} channel=${r})`),a=A(n,i,t,r)??D(n)}if(!a){let o=i||r==="canary"?$(n,i,r):`${n}-<version>.bundle.min.mjs`;process.stderr.write(`entrypoint: could not resolve the ${n} runtime bundle (${o}).
  Looked in cache ${t} and repo-root dist/.
  The bundle ships as a GitHub Release asset (ADR 0034) fetched by red-fetch;
  ensure network access on first run, or build it locally:
    pnpm -C apps/${n} run bundle
`),process.exit(1)}let s=te(process.execPath,[a,...e.rest],{stdio:"inherit"});s.signal&&process.kill(process.pid,s.signal),process.exit(s.status??1)}var he=`entrypoint (fetch) \u2014 resolve a plugin's built bundle from its GitHub Release into a local cache.

Usage:
  node <entrypoint> fetch <plugin> <version> [--repo owner/name] [--cache-dir DIR]
  node red-fetch.mjs       <plugin> <version> [--repo owner/name] [--cache-dir DIR]

Arguments:
  <plugin>     plugin name (e.g. dev, memory)
  <version>    plugin version without the leading v (e.g. 1.140.0)

Options:
  --repo       GitHub repo publishing the release (default: ${w})
  --cache-dir  override the bundle cache dir
  -h, --help   show this help

Best-effort: never blocks session start. On any failure it logs to
<cache-dir>/red-fetch.log and exits 0.`;async function ge(e){let n=N(e.cacheDir);(e.help||!e.plugin||!e.version)&&(process.stdout.write(`${he}
`),!e.help&&(!e.plugin||!e.version)&&process.stdout.write(`
entrypoint: missing <plugin> and/or <version>; nothing to do.
`),process.exit(0));let{plugin:t,version:i}=e;R(process.cwd(),t)||process.exit(0);let r=H(process.env,j()),a=m({plugin:t,version:i,cacheDir:n,channel:r});try{let s=await v(S,{plugin:t,version:i,repo:e.repo,cacheDir:n,channel:r});process.stdout.write(`entrypoint: bundle ready at ${s} (${r})
`)}catch(s){let o=s instanceof c?s.kind:"unknown",l=s instanceof Error?s.message:String(s);await U(n,`${o}: ${l} (fetch plugin=${t} version=${i} channel=${r})`),process.stdout.write(`entrypoint: could not fetch ${t}@${i} (${o}); expected cache path ${a}. Continuing \u2014 fetch is best-effort.
`)}process.exit(0)}async function me(){let e=ue(process.argv.slice(2),le());e.mode==="run"?await pe(e):await ge(e)}import.meta.url===`file://${process.argv[1]}`&&me();export{de as configuredChannelValue,ue as parseEntrypoint,H as resolveLauncherChannel};
