import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import type { ReleaseTrigger } from "./version-surfaces.js";
import { readReleaseConfig } from "./version-surfaces.js";

export const RELEASE_WORKFLOW_PATH = ".github/workflows/red-release.yml";

const CHECKOUT_ACTION = "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5";
const SETUP_NODE_ACTION = "actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020";
const RELEASE_BOT = "red-skills-release[bot]";

export interface RenderReleaseWorkflowInput {
  readonly trigger: ReleaseTrigger;
  readonly engineVersion: string;
}

export interface GenerateReleaseWorkflowsInput {
  readonly repoRoot: string;
  readonly engineVersion: string;
}

export interface GenerateReleaseWorkflowsResult {
  readonly path: string;
  readonly changed: boolean;
  readonly trigger: ReleaseTrigger;
  readonly engineVersion: string;
}

/** Render the complete pinned-execution workflow for one configured trigger. */
export function renderReleaseWorkflow(input: RenderReleaseWorkflowInput): string {
  const invocation = pinnedInvocation(input.engineVersion);
  return input.trigger === "version-pr"
    ? renderVersionPullRequestWorkflow(invocation)
    : renderAutoWorkflow(invocation);
}

/**
 * Converge the generated workflow from `.red/config.yaml`.
 *
 * Exact byte comparison makes a repeated setup run a true no-op. Passing the
 * newer engine's version changes only the canonical npm pin in otherwise
 * identical generated bytes.
 */
export function generateReleaseWorkflows(
  input: GenerateReleaseWorkflowsInput,
): GenerateReleaseWorkflowsResult {
  const repoRoot = resolve(input.repoRoot);
  const config = readReleaseConfig(repoRoot);
  const source = renderReleaseWorkflow({
    trigger: config.trigger,
    engineVersion: input.engineVersion,
  });
  const path = join(repoRoot, RELEASE_WORKFLOW_PATH);
  const previous = existsSync(path) ? readFileSync(path, "utf8") : undefined;
  const changed = previous !== source;
  if (changed) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, source, "utf8");
  }
  return {
    path,
    changed,
    trigger: config.trigger,
    engineVersion: normalizedEngineVersion(input.engineVersion),
  };
}

function pinnedInvocation(engineVersion: string): string {
  const version = normalizedEngineVersion(engineVersion);
  return `npx -y -p @reddb-io/red-skills@${version} red-skills-release run`;
}

function normalizedEngineVersion(value: string): string {
  const version = value.trim().replace(/^v/, "");
  if (!/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(version)) {
    throw new Error(`release workflow engine version must be an exact stable semver: ${value}`);
  }
  return version;
}

function renderVersionPullRequestWorkflow(invocation: string): string {
  return [
    generatedHeader(),
    "name: RedSkills Release",
    "",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "    branches: [main]",
    "    types: [closed]",
    "",
    "permissions: {}",
    "",
    "jobs:",
    "  maintain-version-pr:",
    `    if: github.event_name == 'push' && github.event.head_commit.author.name != '${RELEASE_BOT}'`,
    "    runs-on: ubuntu-latest",
    "    permissions:",
    "      contents: write",
    "      pull-requests: write",
    "    steps:",
    `      - uses: ${CHECKOUT_ACTION}`,
    "        with:",
    "          fetch-depth: 0",
    `      - uses: ${SETUP_NODE_ACTION}`,
    "        with:",
    "          node-version: 22",
    "      - name: Maintain Version PR",
    "        env:",
    "          GITHUB_TOKEN: ${{ github.token }}",
    `        run: ${invocation}`,
    "",
    "  publish-release:",
    "    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'red-release/version-pr'",
    "    runs-on: ubuntu-latest",
    "    permissions:",
    "      contents: write",
    "    steps:",
    `      - uses: ${CHECKOUT_ACTION}`,
    "        with:",
    "          fetch-depth: 0",
    "          ref: ${{ github.event.pull_request.merge_commit_sha }}",
    `      - uses: ${SETUP_NODE_ACTION}`,
    "        with:",
    "          node-version: 22",
    "      - name: Publish Release",
    "        env:",
    "          GITHUB_TOKEN: ${{ github.token }}",
    `        run: ${invocation}`,
    "",
  ].join("\n");
}

function renderAutoWorkflow(invocation: string): string {
  return [
    generatedHeader(),
    "name: RedSkills Release",
    "",
    "on:",
    "  push:",
    "    branches: [main]",
    "",
    "permissions: {}",
    "",
    "jobs:",
    "  publish-release:",
    `    if: github.event.head_commit.author.name != '${RELEASE_BOT}'`,
    "    runs-on: ubuntu-latest",
    "    permissions:",
    "      contents: write",
    "    steps:",
    `      - uses: ${CHECKOUT_ACTION}`,
    "        with:",
    "          fetch-depth: 0",
    `      - uses: ${SETUP_NODE_ACTION}`,
    "        with:",
    "          node-version: 22",
    "      - name: Publish Release",
    "        env:",
    "          GITHUB_TOKEN: ${{ github.token }}",
    `        run: ${invocation}`,
    "",
  ].join("\n");
}

function generatedHeader(): string {
  return "# Generated by red-skills-release. Re-run /red-setup to refresh this file.";
}
